### ISSUE TITLE
Can't load webviews

### ISSUE THREAD

**Issue by pdeffebach** [joa-quim/Webview.jl#1]
```
julia> webview1 = Webview()
ERROR: could not load library "libwebkit2gtk-4.0.so.37"
/home/peterwd/.julia/juliaup/julia-1.8.3+0.x64.linux.gnu/bin/../lib/julia/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /lib/x86_64-linux-gnu/libjavascriptcoregtk-4.0.so.18)
```

I'm interested in using this package to replace Blink.jl in my package [FloatingTableView.jl](https://github.com/pdeffebach/FloatingTableView.jl/issues). 

But I can't get it to work. 

This is after installing via the command in the readme (Ubuntu 22) and calling `build`. 

Thanks!

How hard would it be to just use BinaryBuilder and JLLs for everything?

**Comment by joa-quim** [comment]
That  error is a *plague* and is a consequence on how Linux is so light in breaking compatibility. The reason is that Julia ships with an older and now incompatible ``libstdc++`` library. The problem should be solve with Julia v1.9 (but not 1.8).

Also, I have not touched this package for a long time and recently there was this announcement in the Julia forum. Probably of interest for you.

https://discourse.julialang.org/t/ann-webviews-jl-a-tiny-library-for-creating-web-based-desktop-guis/91406

**Comment by pdeffebach** [comment]
Oh wait! I filed an issue in the wrong repo! You are still the top hit on google. 

Sorry for the noise.

**Comment by joa-quim** [comment]
No problem, but probably my answer applies exactly the same to the other package.

**Comment by pdeffebach** [comment]
Indeed.
